export const USER_SIGNUP_ENDPOINT = "/users/signup/";
export const USER_LOGIN_ENDPOINT = "/users/login/";
export const USER_BOARDS_ENDPOINT = "/tm/boards";
export const USER_TASKS_ENDPOINT = "/tm/tasks-by-boardid";
export const USER_CREATEBOARD_ENDPOINT = "/tm/create-board";
export const USER_ADDTASK_ENDPOINT = "/tm/add-task";
export const USER_DELETETASK_ENDPOINT = "/tm/delete-task";
export const USER_EDITTASK_ENDPOINT = "/tm/edit-task";
export const USER_DELETEBOARD_ENDPOINT="/tm/delete-board";
